import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, FileText, Download, AlertCircle, Crown, RefreshCw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { toast } from "sonner";
import { subscriptionsApi, invoicesApi, refundsApi } from "@/services/billing";
import { useAuth } from "@/hooks/useAuth";
import { useTranslation } from "react-i18next";

const STATUS_COLORS: Record<string, string> = {
  active: "bg-scarab/20 text-scarab",
  trialing: "bg-nile/20 text-nile",
  past_due: "bg-primary/20 text-primary",
  cancelled: "bg-muted text-muted-foreground",
  suspended: "bg-blood-red/20 text-blood-red",
  paid: "bg-scarab/20 text-scarab",
  pending: "bg-primary/20 text-primary",
  failed: "bg-blood-red/20 text-blood-red",
  refunded: "bg-muted text-muted-foreground",
};

const CustomerPortal = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { t } = useTranslation();
  const [subs, setSubs] = useState<any[]>([]);
  const [invs, setInvs] = useState<any[]>([]);
  const [refundFor, setRefundFor] = useState<any | null>(null);
  const [refundReason, setRefundReason] = useState("");

  const load = () => Promise.all([subscriptionsApi.list(), invoicesApi.list()]).then(([s, i]) => { setSubs(s); setInvs(i); });
  useEffect(() => { if (user) load(); }, [user]);

  const cancelSub = async (id: string) => {
    if (!confirm(t("cancel_subscription") + "?")) return;
    try { await subscriptionsApi.cancel(id); toast.success("Subscription cancelled"); load(); }
    catch (e: any) { toast.error(e.message); }
  };

  const submitRefund = async () => {
    if (!refundFor) return;
    try {
      await refundsApi.create({
        invoice_id: refundFor.id, amount: refundFor.total, currency: refundFor.currency, reason: refundReason,
      });
      toast.success("Refund request submitted");
      setRefundFor(null); setRefundReason("");
    } catch (e: any) { toast.error(e.message); }
  };

  const downloadInvoice = (inv: any) => {
    const html = `<html><head><meta charset="utf-8"><title>${inv.invoice_number}</title>
      <style>body{font-family:system-ui;padding:40px;color:#1a1a1a}h1{color:#c9a84c}table{width:100%;border-collapse:collapse;margin:20px 0}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}.r{text-align:right}.tot{font-size:18px;font-weight:bold;color:#c9a84c}</style></head>
      <body><h1>INVOICE</h1>
      <p><strong>${inv.invoice_number}</strong> · ${new Date(inv.created_at).toLocaleDateString()}</p>
      <p>Status: <strong>${inv.status.toUpperCase()}</strong></p>
      <table><thead><tr><th>Item</th><th class="r">Amount</th></tr></thead><tbody>
      ${(inv.line_items || []).map((l: any) => `<tr><td>${l.description}</td><td class="r">${inv.currency} ${l.price}</td></tr>`).join("")}
      <tr><td>Subtotal</td><td class="r">${inv.currency} ${inv.amount}</td></tr>
      ${inv.discount_amount > 0 ? `<tr><td>Discount</td><td class="r">-${inv.currency} ${inv.discount_amount}</td></tr>` : ""}
      ${inv.tax_amount > 0 ? `<tr><td>Tax</td><td class="r">${inv.currency} ${inv.tax_amount}</td></tr>` : ""}
      <tr><td class="tot">TOTAL</td><td class="r tot">${inv.currency} ${inv.total}</td></tr>
      </tbody></table>
      <p style="margin-top:40px;color:#888;font-size:12px">Generated by KemetRise · ${new Date().toLocaleString()}</p>
      </body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = `${inv.invoice_number}.html`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background p-4 md:p-8">
      <div className="max-w-5xl mx-auto">
        <button onClick={() => navigate("/")} className="flex items-center gap-2 text-muted-foreground hover:text-primary mb-6">
          <ArrowLeft className="w-4 h-4" /><span className="text-sm">{t("back")}</span>
        </button>
        <h1 className="font-display text-xl text-primary mb-6">{t("customer_portal").toUpperCase()}</h1>

        <section className="mb-8">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-display text-sm text-primary flex items-center gap-2"><Crown className="w-4 h-4" />{t("my_subscriptions").toUpperCase()} ({subs.length})</h2>
            <Button size="sm" variant="outline" onClick={() => navigate("/pricing")} className="font-display text-xs">+ {t("subscribe")}</Button>
          </div>
          <div className="space-y-2">
            {subs.length === 0 && <p className="text-xs text-muted-foreground p-4 bg-secondary/30 rounded-lg border border-border">{t("no_results")}</p>}
            {subs.map(s => (
              <div key={s.id} className="bg-card border border-border rounded-lg p-4 flex items-center gap-3">
                <Crown className="w-5 h-5 text-primary shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-display text-sm text-foreground">{s.plan_name}</p>
                  <p className="text-[11px] text-muted-foreground">{s.currency} {s.price} / {t(s.interval as any)} · {t("next_billing")}: {new Date(s.current_period_end).toLocaleDateString()}</p>
                </div>
                <span className={`text-[10px] px-2 py-0.5 rounded-full font-display ${STATUS_COLORS[s.status] || "bg-muted"}`}>{s.status.toUpperCase()}</span>
                {s.status !== "cancelled" && (
                  <Button size="sm" variant="ghost" onClick={() => cancelSub(s.id)} className="text-xs text-blood-red">{t("cancel")}</Button>
                )}
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="font-display text-sm text-primary mb-3 flex items-center gap-2"><FileText className="w-4 h-4" />{t("my_invoices").toUpperCase()} ({invs.length})</h2>
          <div className="space-y-2">
            {invs.length === 0 && <p className="text-xs text-muted-foreground p-4 bg-secondary/30 rounded-lg border border-border">{t("no_results")}</p>}
            {invs.map(inv => (
              <div key={inv.id} className="bg-card border border-border rounded-lg p-4 flex items-center gap-3">
                <FileText className="w-4 h-4 text-primary shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-display text-foreground">{inv.invoice_number}</p>
                  <p className="text-[11px] text-muted-foreground">{new Date(inv.created_at).toLocaleDateString()} · {inv.currency} {inv.total}</p>
                </div>
                <span className={`text-[10px] px-2 py-0.5 rounded-full font-display ${STATUS_COLORS[inv.status] || "bg-muted"}`}>{inv.status.toUpperCase()}</span>
                <Button size="sm" variant="ghost" onClick={() => downloadInvoice(inv)} className="text-xs gap-1"><Download className="w-3.5 h-3.5" />{t("download_invoice")}</Button>
                {inv.status === "paid" && (
                  <Button size="sm" variant="ghost" onClick={() => setRefundFor(inv)} className="text-xs gap-1 text-blood-red"><RefreshCw className="w-3.5 h-3.5" />{t("request_refund")}</Button>
                )}
              </div>
            ))}
          </div>
        </section>

        <Dialog open={!!refundFor} onOpenChange={(o) => !o && setRefundFor(null)}>
          <DialogContent className="bg-card border-border max-w-md">
            <DialogHeader><DialogTitle className="font-display text-primary flex items-center gap-2"><AlertCircle className="w-4 h-4" />{t("request_refund")}</DialogTitle></DialogHeader>
            {refundFor && (
              <div className="space-y-3">
                <p className="text-sm text-muted-foreground"><strong className="text-foreground">{refundFor.invoice_number}</strong> — {refundFor.currency} {refundFor.total}</p>
                <div className="space-y-1"><Label className="text-xs">{t("reason")} *</Label><Textarea value={refundReason} onChange={e => setRefundReason(e.target.value)} className="bg-secondary border-border min-h-[100px]" /></div>
              </div>
            )}
            <DialogFooter>
              <Button variant="ghost" onClick={() => setRefundFor(null)}>{t("cancel")}</Button>
              <Button onClick={submitRefund} disabled={!refundReason.trim()} className="font-display text-xs">{t("save")}</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
};

export default CustomerPortal;
