-- ════════════════════════════════════════════════════════════════════════════
-- AI Digital Product Factory — Schema Extension
-- File: supabase/migrations/20260706000000_ai_product_factory.sql
-- Depends on: mp_listings, mp_purchases, user_profiles, notifications (already exist)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Draft products generated by the AI, pre-publish ─────────────────────────
CREATE TABLE IF NOT EXISTS aidpf_products (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id            UUID NOT NULL,                         -- ties back to one n8n workflow execution
  name              TEXT NOT NULL,
  slug              TEXT,
  description       TEXT,
  long_description  TEXT,
  category          TEXT,
  sub_category      TEXT,
  tags              TEXT[] DEFAULT '{}',
  thumbnail_url     TEXT,
  gallery_urls      TEXT[] DEFAULT '{}',
  price_cents       INTEGER NOT NULL DEFAULT 0,
  currency          TEXT NOT NULL DEFAULT 'USD',
  pricing_model     TEXT NOT NULL DEFAULT 'one_time'
                      CHECK (pricing_model IN ('free','one_time','monthly','annual','contact')),
  file_path         TEXT,                                  -- object path in the private 'ai-digital-products' bucket
  file_size_bytes   BIGINT,
  file_type         TEXT,
  meta              JSONB NOT NULL DEFAULT '{}',            -- version, license_type, prompt_used, model_used, generation_cost_usd...
  status            TEXT NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','in_review','approved','rejected','published','failed')),
  listing_id        UUID REFERENCES mp_listings(id) ON DELETE SET NULL,  -- set once published
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Multi-tier approval state machine ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS aidpf_approval_queue (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id         UUID NOT NULL REFERENCES aidpf_products(id) ON DELETE CASCADE,
  run_id             UUID NOT NULL,
  tier               INTEGER NOT NULL DEFAULT 1 CHECK (tier IN (1,2,3)),
  status             TEXT NOT NULL DEFAULT 'awaiting_tier1'
                       CHECK (status IN (
                         'awaiting_tier1','awaiting_tier2','auto_fallback',
                         'approved','rejected','expired'
                       )),
  super_admin_id     UUID REFERENCES auth.users(id),
  tier2_candidate_ids UUID[] NOT NULL DEFAULT '{}',          -- the two team members eligible in Tier 2
  decided_by         UUID REFERENCES auth.users(id),          -- who actually made the final decision (or null if auto-fallback)
  decision           TEXT CHECK (decision IN ('approved','rejected')),
  decision_tier      INTEGER,                                 -- which tier the decision was made at (1, 2, or 3=auto)
  tier1_deadline     TIMESTAMPTZ,
  tier2_deadline     TIMESTAMPTZ,
  n8n_execution_id   TEXT,                                    -- n8n workflow execution id, for resume-webhook correlation
  n8n_resume_url_t1  TEXT,                                    -- the Wait node's resume webhook URL for tier 1
  n8n_resume_url_t2  TEXT,                                    -- the Wait node's resume webhook URL for tier 2
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Every individual click/response, for audit + "first responder wins" logic
CREATE TABLE IF NOT EXISTS aidpf_approval_responses (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  queue_id       UUID NOT NULL REFERENCES aidpf_approval_queue(id) ON DELETE CASCADE,
  tier           INTEGER NOT NULL,
  responder_id   UUID REFERENCES auth.users(id),
  decision       TEXT NOT NULL CHECK (decision IN ('approved','rejected')),
  note           TEXT,
  responded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Only the FIRST response per (queue_id, tier) should count — enforced in the edge function via
-- an atomic UPDATE ... WHERE status = 'awaiting_tierN' (see ai-factory-approval-webhook function).

-- ── Secure, single-use / expiring download tokens for purchased digital goods
CREATE TABLE IF NOT EXISTS aidpf_download_tokens (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token         TEXT NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(32), 'hex'),
  product_id    UUID NOT NULL REFERENCES aidpf_products(id) ON DELETE CASCADE,
  purchase_id   UUID NOT NULL REFERENCES mp_purchases(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES auth.users(id),
  max_uses      INTEGER NOT NULL DEFAULT 5,
  use_count     INTEGER NOT NULL DEFAULT 0,
  expires_at    TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Full generation + pipeline log (idea gen, image gen, listing, errors) ───
CREATE TABLE IF NOT EXISTS aidpf_generation_logs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id      UUID NOT NULL,
  product_id  UUID REFERENCES aidpf_products(id) ON DELETE CASCADE,
  step        TEXT NOT NULL,               -- 'idea_generation' | 'content_generation' | 'image_generation' | 'approval_tier1' | 'approval_tier2' | 'auto_fallback' | 'publish' | 'social_post' | 'error'
  level       TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('info','warning','error')),
  message     TEXT,
  payload     JSONB DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Autonomous traffic engine: social posts / DMs fired per published product
CREATE TABLE IF NOT EXISTS aidpf_traffic_posts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id    UUID NOT NULL REFERENCES aidpf_products(id) ON DELETE CASCADE,
  channel       TEXT NOT NULL,             -- 'instagram' | 'facebook' | 'x' | 'whatsapp_dm' | 'telegram'
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','posted','failed')),
  external_post_id TEXT,
  response_body TEXT,
  posted_at     TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Factory-wide config (super admin id, tier2 pool, timeouts) — one row ────
CREATE TABLE IF NOT EXISTS aidpf_settings (
  id                    INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  super_admin_id        UUID REFERENCES auth.users(id),
  tier2_pool_ids        UUID[] NOT NULL DEFAULT '{}',   -- pick 2 from this pool per run (or set a fixed pair)
  tier1_timeout_minutes INTEGER NOT NULL DEFAULT 120,
  tier2_timeout_minutes INTEGER NOT NULL DEFAULT 120,
  is_factory_active     BOOLEAN NOT NULL DEFAULT true,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO aidpf_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS aidpf_products_status_idx        ON aidpf_products(status);
CREATE INDEX IF NOT EXISTS aidpf_products_run_idx           ON aidpf_products(run_id);
CREATE INDEX IF NOT EXISTS aidpf_approval_queue_status_idx  ON aidpf_approval_queue(status);
CREATE INDEX IF NOT EXISTS aidpf_approval_queue_product_idx ON aidpf_approval_queue(product_id);
CREATE INDEX IF NOT EXISTS aidpf_responses_queue_idx        ON aidpf_approval_responses(queue_id, tier);
CREATE INDEX IF NOT EXISTS aidpf_tokens_token_idx           ON aidpf_download_tokens(token);
CREATE INDEX IF NOT EXISTS aidpf_tokens_expiry_idx          ON aidpf_download_tokens(expires_at);
CREATE INDEX IF NOT EXISTS aidpf_logs_run_idx               ON aidpf_generation_logs(run_id, created_at);
CREATE INDEX IF NOT EXISTS aidpf_traffic_product_idx        ON aidpf_traffic_posts(product_id);

-- ── updated_at triggers (reuse existing helper if you have one; else inline) ─
CREATE OR REPLACE FUNCTION aidpf_touch_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_aidpf_products_touch ON aidpf_products;
CREATE TRIGGER trg_aidpf_products_touch BEFORE UPDATE ON aidpf_products
  FOR EACH ROW EXECUTE FUNCTION aidpf_touch_updated_at();

DROP TRIGGER IF EXISTS trg_aidpf_queue_touch ON aidpf_approval_queue;
CREATE TRIGGER trg_aidpf_queue_touch BEFORE UPDATE ON aidpf_approval_queue
  FOR EACH ROW EXECUTE FUNCTION aidpf_touch_updated_at();

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE aidpf_products           ENABLE ROW LEVEL SECURITY;
ALTER TABLE aidpf_approval_queue     ENABLE ROW LEVEL SECURITY;
ALTER TABLE aidpf_approval_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE aidpf_download_tokens    ENABLE ROW LEVEL SECURITY;
ALTER TABLE aidpf_generation_logs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE aidpf_traffic_posts      ENABLE ROW LEVEL SECURITY;
ALTER TABLE aidpf_settings           ENABLE ROW LEVEL SECURITY;

-- Admin/superadmin full read on everything factory-related (matches your existing role check pattern)
CREATE POLICY aidpf_products_admin_all ON aidpf_products FOR ALL
  USING (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')))
  WITH CHECK (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')));

CREATE POLICY aidpf_queue_admin_all ON aidpf_approval_queue FOR ALL
  USING (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')))
  WITH CHECK (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')));

-- Tier-2 approvers can see + respond to ONLY the queue rows where they're a listed candidate
CREATE POLICY aidpf_queue_tier2_read ON aidpf_approval_queue FOR SELECT
  USING (auth.uid() = ANY(tier2_candidate_ids));

CREATE POLICY aidpf_responses_admin_all ON aidpf_approval_responses FOR ALL
  USING (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')));

CREATE POLICY aidpf_responses_self_insert ON aidpf_approval_responses FOR INSERT
  WITH CHECK (auth.uid() = responder_id);

CREATE POLICY aidpf_logs_admin_read ON aidpf_generation_logs FOR SELECT
  USING (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')));

CREATE POLICY aidpf_traffic_admin_read ON aidpf_traffic_posts FOR SELECT
  USING (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')));

CREATE POLICY aidpf_settings_admin_all ON aidpf_settings FOR ALL
  USING (EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = auth.uid() AND up.role IN ('admin','superadmin')));

-- A purchaser may read only their own download tokens
CREATE POLICY aidpf_tokens_owner_read ON aidpf_download_tokens FOR SELECT
  USING (auth.uid() = user_id);

-- NOTE: all INSERT/UPDATE from n8n happens through the edge functions below using the
-- SERVICE ROLE KEY, which bypasses RLS entirely — that is intentional and is the only
-- way n8n should ever touch these tables. Never give n8n the anon or user JWT.

-- ── Storage bucket for raw product files (private; served only via signed URLs) ─
INSERT INTO storage.buckets (id, name, public)
VALUES ('ai-digital-products', 'ai-digital-products', false)
ON CONFLICT (id) DO NOTHING;

-- Only service_role (edge functions) may read/write the bucket directly.
-- Buyers get access exclusively through short-lived signed URLs minted by
-- the ai-factory-download edge function after verifying mp_purchases ownership.
CREATE POLICY aidpf_bucket_service_only ON storage.objects FOR ALL
  USING (bucket_id = 'ai-digital-products' AND auth.role() = 'service_role')
  WITH CHECK (bucket_id = 'ai-digital-products' AND auth.role() = 'service_role');

-- ════════════════════════════════════════════════════════════════════════════
-- Auto-publish: the moment a product's approval decision (from any tier) is
-- recorded as 'approved', flip the product to 'approved' status. The actual
-- INSERT into mp_listings is done by the ai-factory-publish edge function
-- (not a DB trigger) because it also needs to upload/verify the storage file
-- and call out to the notifications table — logic that's easier to keep in
-- one auditable place than split across SQL + Deno.
-- ════════════════════════════════════════════════════════════════════════════
